server:
  port: 9191

#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: IssueBill-Service
#          uri: lb://IssueBill-Service
#          predicates:
#            - Path=/allIssueBills/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: IssueBill-Service
#                fallbackuri: forward:/issueBillsFallBack
#        - id: SetRates
#          uri: lb://SetRates
#          predicates:
#            - Path=/allSetRates/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: SetRates
#                fallbackuri: forward:/setRatesFallBack

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: IssueBill-Service
          uri: lb://IssueBill-Service
          predicates:
            - Path=/allIssueBills/**
          filters:
            - name: CircuitBreaker
              args:
                name: IssueBill-Service
                fallbackuri: forward:/issueBillsFallBack
        - id: SetRates
          uri: lb://SetRates
          predicates:
            - Path=/allSetRates/**
          filters:
            - name: CircuitBreaker
              args:
                name: SetRates
                fallbackuri: forward:/setRatesFallBack





hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost



